### ISSUE TITLE
Coin rotation never stops 

### ISSUE THREAD

**Issue by nmondal** [abhishekshah1998/CoinToss#1]
1. Install NOX player
2. Use api - and toss the coin.
3. It does not stop rotating.

**Comment by abhishekshah1998** [comment]
![image](https://user-images.githubusercontent.com/23608784/85205897-f26ea000-b33b-11ea-9e5e-a598b171c8bb.png)

Sir, I have been using [https://developer.android.com/reference/android/view/MotionEvent#getPressure(int)](https://developer.android.com/reference/android/view/MotionEvent#getPressure(int))
method to capture the pressure of the Screen Touch activity. While this feature is supported on only a few newer android models which give the pressure value between 0.0-1.0, all other older android devices return the value 1.0 for touch activity.

The coin doesn't stop rotating because of the screen pressure measured as 1.0, which generates 814 rotations, which would take more than a minute or two to stop rotating.

Please check the below screenshots, taken on a newer android phone. 
![WhatsApp Image 2020-06-20 at 9 28 47 PM](https://user-images.githubusercontent.com/23608784/85206099-49c14000-b33d-11ea-897a-4c2d252515db.jpeg)
![WhatsApp Image 2020-06-20 at 9 28 48 PM](https://user-images.githubusercontent.com/23608784/85206101-4d54c700-b33d-11ea-81f1-0fc5f3295bd1.jpeg)
![WhatsApp Image 2020-06-20 at 9 28 49 PM](https://user-images.githubusercontent.com/23608784/85206103-4f1e8a80-b33d-11ea-85ff-29a6b7db4445.jpeg)
